JNG-4547 Release epsilon-maven-plugin
BlackBeltTechnology/epsilon-maven-plugin pull request #42
Opened 2023-03-07 14:54 UTC by gaborflorian

<table>
<td>
  <a href="https://blackbelt.atlassian.net/browse/JNG-4547" title="JNG-4547" target="_blank"><img alt="Sub-task" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />JNG-4547</a>  Release epsilon-maven-plugin
  </td></table>
  <br />

2023-03-09 12:53 UTC, bencegelei requested changes
java 11?

2023-03-09 12:54 UTC, noherczeg requested changes

2023-03-09 12:54 UTC, noherczeg commented on .buildkite/build.sh
> +mvn clean deploy -DaltDeploymentRepository=blackbelt-nexus-distribution::default::${NEXUS3_URL}/repository/maven-epsilon-maven-plugin-release
"epsilon-maven-plugin"

2023-03-10 13:38 UTC, gaborflorian commented on .buildkite/build.sh
> +mvn clean deploy -DaltDeploymentRepository=blackbelt-nexus-distribution::default::${NEXUS3_URL}/repository/maven-epsilon-maven-plugin-release
[34b0901](https://github.com/BlackBeltTechnology/epsilon-maven-plugin/pull/42/commits/34b090102772661dce26a6a5248d80818360b7e0)

2023-03-10 13:53 UTC, noherczeg requested changes
Wrong license file

2023-03-10 13:53 UTC, noherczeg commented on .buildkite/build.sh
> +mvn clean deploy -DaltDeploymentRepository=blackbelt-nexus-distribution::default::${NEXUS3_URL}/repository/epsilon-maven-plugin-release
We don't use buildkite any more. File should be deleted.

2023-03-10 13:53 UTC, noherczeg commented on pom.xml
> +                                    <licenseName>apache_v2</licenseName>
Should be epl.

2023-03-10 14:33 UTC, bencegelei approved these changes

2023-03-13 08:59 UTC, robertcsakany approved these changes

2023-03-13 10:32 UTC, noherczeg approved these changes

2023-03-13 13:58 UTC, merged